# mabuelgh - Sep 2025

name: vllm-and-open-webui
services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    command: --model /app/model/
    volumes:
      - ./models/Phi-4-mini-instruct:/app/model
    ports:
      - "8000:8000"
    restart: always
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui-for-vllm
    volumes:
    - ./open-webui:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://vllm:8000/v1
      - OFFLINE_MODE=true
      - OPENAI_API_KEY=none
      - WEBUI_AUTH=false
    restart: always