services:
  # We need to first deploy OpenWebUI with WEBUI_AUTH=false then update it to add a user to automate creation of RAG environment.
  # Basically we simply add WEBUI_ADMIN_EMAIL=admin@example.com and WEBUI_ADMIN_PASSWORD=yourpassword
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
    - ./open-webui:/app/backend/data
    ports:
      - "3001:8080"
    environment:
      - OPENAI_API_BASE_URL=http://vllm-mistral:8001/v1
      - OFFLINE_MODE=true
      - OPENAI_API_KEY=none
      - WEBUI_AUTH=false
      - WEBUI_ADMIN_EMAIL=admin@example.com
      - WEBUI_ADMIN_PASSWORD=yourpassword
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_EMBEDDING_MODEL=/app/model/rag
      - RAG_OPENAI_API_BASE_URL=http://vllm-embedding:8000/v1
      - CHUNK_SIZE=300
      - CHUNK_OVERLAP=30
      - RAG_EMBEDDING_CONCURRENT_REQUESTS=2
    restart: always