apiVersion: v1
kind: Pod
metadata:
  name: gpu-burn-pod
spec:
  restartPolicy: OnFailure
  securityContext:
    runAsUser: 0 # This requests the container to run as root
  containers:
    - name: gpu-burn
      image: chrstnhntschl/gpu_burn:latest # Or another suitable image like oguzpastirmaci/gpu-burn:latest
      command: ["./gpu_burn"]
      args: ["60"] # Run gpu_burn for 60 seconds
      resources:
        limits:
          nvidia.com/gpu: 1 # Request 1 GPU
  nodeSelector:
    nvidia.com/gpu.present: "true"